insert into customer_address (customer_id, firstname, lastname, street_1, postcode, city, country_id) values (1, 'Cosette', 'Crosgrove', '65 Gerald Center', null, 'Nanfeng', 'CN');
insert into customer_address (customer_id, firstname, lastname, street_1, postcode, city, country_id) values (2, 'Dolly', 'Ianetti', '9595 Northwestern Lane', '9500', 'General Santos', 'PH');
insert into customer_address (customer_id, firstname, lastname, street_1, postcode, city, country_id) values (3, 'Genni', 'Nusche', '0 Corry Terrace', '249432', 'Zhigalovo', 'RU');
insert into customer_address (customer_id, firstname, lastname, street_1, postcode, city, country_id) values (4, 'Beulah', 'Rubberts', '50161 Ryan Center', '48-120', 'Baborów', 'PL');
insert into customer_address (customer_id, firstname, lastname, street_1, postcode, city, country_id) values (5, 'Johannes', 'Edelston', '8 Prairie Rose Point', null, 'Jinglou', 'CN');
insert into customer_address (customer_id, firstname, lastname, street_1, postcode, city, country_id) values (6, 'Jordana', 'Kelshaw', '3581 Pepper Wood Junction', '93094', 'Simi Valley', 'US');
insert into customer_address (customer_id, firstname, lastname, street_1, postcode, city, country_id) values (7, 'Odie', 'Cock', '71 Calypso Drive', '50130', 'San Kamphaeng', 'TH');
insert into customer_address (customer_id, firstname, lastname, street_1, postcode, city, country_id) values (8, 'Sayre', 'Behn', '589 Dunning Road', '72-210', 'Dobra', 'PL');
insert into customer_address (customer_id, firstname, lastname, street_1, postcode, city, country_id) values (9, 'Kleon', 'Timmes', '76487 Sommers Point', '35920-000', 'Nova Era', 'BR');
insert into customer_address (customer_id, firstname, lastname, street_1, postcode, city, country_id) values (10, 'Harland', 'Grastye', '9097 Tennyson Circle', null, 'Aibura', 'ID');
insert into customer_address (customer_id, firstname, lastname, street_1, postcode, city, country_id) values (11, 'Janet', 'Cowtherd', '47 Harper Avenue', '63504 CEDEX', 'Issoire', 'FR');
insert into customer_address (customer_id, firstname, lastname, street_1, postcode, city, country_id) values (12, 'Celeste', 'McKyrrelly', '0 Blaine Drive', null, 'Huashixia', 'CN');
insert into customer_address (customer_id, firstname, lastname, street_1, postcode, city, country_id) values (13, 'Kirstyn', 'Coltart', '00 Mendota Pass', '941 28', 'Piteå', 'SE');
insert into customer_address (customer_id, firstname, lastname, street_1, postcode, city, country_id) values (14, 'Evelina', 'Wilfling', '509 Lakewood Circle', '912 99', 'Vilhelmina', 'SE');
insert into customer_address (customer_id, firstname, lastname, street_1, postcode, city, country_id) values (15, 'Friederike', 'Beddis', '8562 Hagan Junction', null, 'Mehtar Lām', 'AF');
insert into customer_address (customer_id, firstname, lastname, street_1, postcode, city, country_id) values (16, 'Miriam', 'Perrelli', '6 Mockingbird Avenue', '24-130', 'Końskowola', 'PL');
insert into customer_address (customer_id, firstname, lastname, street_1, postcode, city, country_id) values (17, 'Harriot', 'Bill', '7 Manufacturers Drive', null, 'Gadang', 'ID');
insert into customer_address (customer_id, firstname, lastname, street_1, postcode, city, country_id) values (18, 'Levy', 'Greaterex', '7 Nevada Center', null, 'Naikoten Dua', 'ID');
insert into customer_address (customer_id, firstname, lastname, street_1, postcode, city, country_id) values (19, 'Ruthann', 'Cutriss', '21 American Trail', null, 'Jatiwangi', 'ID');
insert into customer_address (customer_id, firstname, lastname, street_1, postcode, city, country_id) values (20, 'Nanci', 'Miquelet', '55239 Mesta Junction', null, 'Bebae', 'ID');
insert into customer_address (customer_id, firstname, lastname, street_1, postcode, city, country_id) values (21, 'Evey', 'Choat', '0076 Sunfield Crossing', '26-337', 'Aleksandrów', 'PL');
insert into customer_address (customer_id, firstname, lastname, street_1, postcode, city, country_id) values (22, 'Joelle', 'Latehouse', '865 Hoard Trail', '58823-000', 'Piuí', 'BR');
insert into customer_address (customer_id, firstname, lastname, street_1, postcode, city, country_id) values (23, 'Liana', 'Guisot', '14448 Algoma Terrace', '188909', 'Vysotsk', 'RU');
insert into customer_address (customer_id, firstname, lastname, street_1, postcode, city, country_id) values (24, 'Janna', 'Cunnington', '30 Schmedeman Crossing', '456922', 'Tol’yatti', 'RU');
insert into customer_address (customer_id, firstname, lastname, street_1, postcode, city, country_id) values (25, 'Luce', 'Tree', '6 Drewry Way', null, 'Thị Trấn Nho Quan', 'VN');
insert into customer_address (customer_id, firstname, lastname, street_1, postcode, city, country_id) values (26, 'Sydelle', 'Whitsun', '474 Ramsey Place', null, 'Sanyang', 'CN');
insert into customer_address (customer_id, firstname, lastname, street_1, postcode, city, country_id) values (27, 'Berti', 'Greystoke', '6246 Morningstar Hill', null, 'Labinot-Mal', 'AL');
insert into customer_address (customer_id, firstname, lastname, street_1, postcode, city, country_id) values (28, 'Susannah', 'Bartlet', '23903 Granby Point', null, 'Mainri', 'CN');
insert into customer_address (customer_id, firstname, lastname, street_1, postcode, city, country_id) values (29, 'Marylynne', 'Wyleman', '510 Arkansas Road', '4500', 'Bascaron', 'PH');
insert into customer_address (customer_id, firstname, lastname, street_1, postcode, city, country_id) values (30, 'Arnoldo', 'Tewkesbury.', '396 Del Sol Circle', 'J9E', 'Maniwaki', 'CA');
insert into customer_address (customer_id, firstname, lastname, street_1, postcode, city, country_id) values (31, 'Onfre', 'Basant', '3 Homewood Place', null, 'Buur Gaabo', 'SO');
insert into customer_address (customer_id, firstname, lastname, street_1, postcode, city, country_id) values (32, 'Biddie', 'Shildrick', '5 Fremont Road', '257 22', 'Čerčany', 'CZ');
insert into customer_address (customer_id, firstname, lastname, street_1, postcode, city, country_id) values (33, 'Otho', 'Mathers', '95767 Hoepker Pass', '30674', 'Ipoh', 'MY');
insert into customer_address (customer_id, firstname, lastname, street_1, postcode, city, country_id) values (34, 'Dory', 'Tomaello', '17022 Rowland Street', null, 'Ceelbuur', 'SO');
insert into customer_address (customer_id, firstname, lastname, street_1, postcode, city, country_id) values (35, 'Tremain', 'Goschalk', '2 Clove Terrace', '501 88', 'Borås', 'SE');
insert into customer_address (customer_id, firstname, lastname, street_1, postcode, city, country_id) values (36, 'Saraann', 'Kubicka', '3343 Dryden Hill', '00100', 'Colombo', 'LK');
insert into customer_address (customer_id, firstname, lastname, street_1, postcode, city, country_id) values (37, 'Torrin', 'Mitrovic', '2 Dorton Hill', null, 'Chengxiang', 'CN');
insert into customer_address (customer_id, firstname, lastname, street_1, postcode, city, country_id) values (38, 'Hulda', 'Larn', '13 Main Trail', null, 'Barvinkove', 'UA');
insert into customer_address (customer_id, firstname, lastname, street_1, postcode, city, country_id) values (39, 'Daisie', 'Slocomb', '01263 Basil Court', null, 'Jinshanwei', 'CN');
insert into customer_address (customer_id, firstname, lastname, street_1, postcode, city, country_id) values (40, 'Katerina', 'Warn', '10 Doe Crossing Center', '62400-000', 'Camocim', 'BR');
insert into customer_address (customer_id, firstname, lastname, street_1, postcode, city, country_id) values (41, 'Isaac', 'MacCarroll', '8 Leroy Point', '303154', 'Znamenskoye', 'RU');
insert into customer_address (customer_id, firstname, lastname, street_1, postcode, city, country_id) values (42, 'Lorrin', 'Gutsell', '64924 Evergreen Hill', null, 'Bantarpanjang', 'ID');
insert into customer_address (customer_id, firstname, lastname, street_1, postcode, city, country_id) values (43, 'Georg', 'Plett', '88511 Sachs Alley', null, 'Subrag', 'CN');
insert into customer_address (customer_id, firstname, lastname, street_1, postcode, city, country_id) values (44, 'Rochelle', 'Rodie', '255 6th Place', null, 'Batan', 'CN');
insert into customer_address (customer_id, firstname, lastname, street_1, postcode, city, country_id) values (45, 'Rene', 'Strettle', '4 Red Cloud Court', null, 'Qiucun', 'CN');
insert into customer_address (customer_id, firstname, lastname, street_1, postcode, city, country_id) values (46, 'Melvin', 'Tweedy', '46 Lindbergh Way', '30150', 'Pak Thong Chai', 'TH');
insert into customer_address (customer_id, firstname, lastname, street_1, postcode, city, country_id) values (47, 'Roobbie', 'Windrass', '4826 Nelson Center', null, 'Siguqiao', 'CN');
insert into customer_address (customer_id, firstname, lastname, street_1, postcode, city, country_id) values (48, 'Hinda', 'Wormstone', '34 Dapin Road', null, 'Kon Tum', 'VN');
insert into customer_address (customer_id, firstname, lastname, street_1, postcode, city, country_id) values (49, 'Chaunce', 'Hunstone', '36608 Troy Drive', '09-135', 'Siemiątkowo', 'PL');
insert into customer_address (customer_id, firstname, lastname, street_1, postcode, city, country_id) values (50, 'Brendin', 'Thibodeaux', '225 Buhler Center', null, 'Sidi Moussa', 'MA');
insert into customer_address (customer_id, firstname, lastname, street_1, postcode, city, country_id) values (51, 'Jennette', 'Edmund', '256 Briar Crest Junction', '249111', 'Tarusa', 'RU');
insert into customer_address (customer_id, firstname, lastname, street_1, postcode, city, country_id) values (52, 'Brett', 'Goodbody', '810 Loftsgordon Circle', '1794', 'Roodepoort', 'ZA');
insert into customer_address (customer_id, firstname, lastname, street_1, postcode, city, country_id) values (53, 'Brittany', 'Apperley', '16095 Comanche Alley', '257 08', 'Načeradec', 'CZ');
insert into customer_address (customer_id, firstname, lastname, street_1, postcode, city, country_id) values (54, 'Nettle', 'Rantoull', '78399 Brown Drive', '16904 CEDEX 9', 'Angoulême', 'FR');
insert into customer_address (customer_id, firstname, lastname, street_1, postcode, city, country_id) values (55, 'Ethelyn', 'Dumbellow', '489 Banding Way', '43-330', 'Wilamowice', 'PL');
insert into customer_address (customer_id, firstname, lastname, street_1, postcode, city, country_id) values (56, 'Woodie', 'Natalie', '17 Rowland Avenue', null, 'Pamoyanan', 'ID');
insert into customer_address (customer_id, firstname, lastname, street_1, postcode, city, country_id) values (57, 'Gretal', 'Williscroft', '85761 Coleman Way', '9104', 'Catarman', 'PH');
insert into customer_address (customer_id, firstname, lastname, street_1, postcode, city, country_id) values (58, 'Nichole', 'Carruthers', '6 Nevada Circle', '3423', 'Zárate', 'AR');
insert into customer_address (customer_id, firstname, lastname, street_1, postcode, city, country_id) values (59, 'Brooks', 'Nucator', '5 Jana Place', '89915-000', 'Santa Helena', 'BR');
insert into customer_address (customer_id, firstname, lastname, street_1, postcode, city, country_id) values (60, 'Allianora', 'Jermyn', '14 Golf Terrace', null, 'Paisha', 'CN');
insert into customer_address (customer_id, firstname, lastname, street_1, postcode, city, country_id) values (61, 'Dale', 'Grafhom', '5 Emmet Drive', null, 'Chinch''ŏn', 'KR');
insert into customer_address (customer_id, firstname, lastname, street_1, postcode, city, country_id) values (62, 'Ilse', 'Hargrave', '148 Iowa Hill', '56000-000', 'Salgueiro', 'BR');
insert into customer_address (customer_id, firstname, lastname, street_1, postcode, city, country_id) values (63, 'Marja', 'Garie', '1 Charing Cross Alley', null, 'Raffingora', 'ZW');
insert into customer_address (customer_id, firstname, lastname, street_1, postcode, city, country_id) values (64, 'Celine', 'Nanelli', '825 Hoffman Alley', null, 'Huang’ao', 'CN');
insert into customer_address (customer_id, firstname, lastname, street_1, postcode, city, country_id) values (65, 'Simone', 'Stayt', '68172 Fair Oaks Road', null, 'Golacir', 'ID');
insert into customer_address (customer_id, firstname, lastname, street_1, postcode, city, country_id) values (66, 'Sheelagh', 'Abelov', '131 Hudson Junction', null, 'Koa', 'ID');
insert into customer_address (customer_id, firstname, lastname, street_1, postcode, city, country_id) values (67, 'Arvin', 'Antonoyev', '3145 Menomonie Circle', null, 'Ganyi', 'CN');
insert into customer_address (customer_id, firstname, lastname, street_1, postcode, city, country_id) values (68, 'Kipp', 'Pinkerton', '512 Novick Court', '763-0231', 'Wakkanai', 'JP');
insert into customer_address (customer_id, firstname, lastname, street_1, postcode, city, country_id) values (69, 'Elyn', 'Grasner', '84539 Mendota Avenue', '92787 CEDEX 9', 'Issy-les-Moulineaux', 'FR');
insert into customer_address (customer_id, firstname, lastname, street_1, postcode, city, country_id) values (70, 'Blayne', 'Tolcher', '23 North Road', null, 'Munturkaju', 'ID');
insert into customer_address (customer_id, firstname, lastname, street_1, postcode, city, country_id) values (71, 'Raquela', 'Arber', '6537 Bayside Street', '569 43', 'Jevíčko', 'CZ');
insert into customer_address (customer_id, firstname, lastname, street_1, postcode, city, country_id) values (72, 'Jessalyn', 'Trayford', '885 Macpherson Trail', null, 'Petauke', 'ZM');
insert into customer_address (customer_id, firstname, lastname, street_1, postcode, city, country_id) values (73, 'Ken', 'Podbury', '147 Cottonwood Plaza', '37650-000', 'Camanducaia', 'BR');
insert into customer_address (customer_id, firstname, lastname, street_1, postcode, city, country_id) values (74, 'Hailee', 'Ruckert', '01310 Ramsey Drive', null, 'Sumberan', 'ID');
insert into customer_address (customer_id, firstname, lastname, street_1, postcode, city, country_id) values (75, 'Yale', 'Agglione', '28844 Manufacturers Street', '55630-000', 'Pombos', 'BR');
insert into customer_address (customer_id, firstname, lastname, street_1, postcode, city, country_id) values (76, 'Eleanor', 'Lassells', '4 Delaware Court', 'V3B', 'Bay Roberts', 'CA');
insert into customer_address (customer_id, firstname, lastname, street_1, postcode, city, country_id) values (77, 'Kaile', 'Piwell', '9028 Alpine Court', null, 'Caozhen', 'CN');
insert into customer_address (customer_id, firstname, lastname, street_1, postcode, city, country_id) values (78, 'Corri', 'Snowling', '2 Sachtjen Circle', null, 'Bartsrashen', 'AM');
insert into customer_address (customer_id, firstname, lastname, street_1, postcode, city, country_id) values (79, 'Calley', 'Blown', '55849 Tennessee Lane', null, 'Sale', 'ID');
insert into customer_address (customer_id, firstname, lastname, street_1, postcode, city, country_id) values (80, 'Maridel', 'Kubasek', '7308 Blackbird Court', null, 'Ambohitseheno', 'MG');
insert into customer_address (customer_id, firstname, lastname, street_1, postcode, city, country_id) values (81, 'Chryste', 'Martel', '8 Farragut Plaza', '4507', 'Alabug', 'PH');
insert into customer_address (customer_id, firstname, lastname, street_1, postcode, city, country_id) values (82, 'Ardith', 'Paulsen', '3412 Marcy Drive', null, 'Leping', 'CN');
insert into customer_address (customer_id, firstname, lastname, street_1, postcode, city, country_id) values (83, 'Cassius', 'Marshalleck', '43 Pine View Hill', '427580', 'Kez', 'RU');
insert into customer_address (customer_id, firstname, lastname, street_1, postcode, city, country_id) values (84, 'Pearline', 'Goghin', '068 Wayridge Way', null, 'Jianxin', 'CN');
insert into customer_address (customer_id, firstname, lastname, street_1, postcode, city, country_id) values (85, 'Emmey', 'Ramalhete', '1 Magdeline Park', null, 'Houping', 'CN');
insert into customer_address (customer_id, firstname, lastname, street_1, postcode, city, country_id) values (86, 'Gaynor', 'Chettoe', '16 Raven Lane', null, 'Huangrangping', 'CN');
insert into customer_address (customer_id, firstname, lastname, street_1, postcode, city, country_id) values (87, 'Juliana', 'Goodere', '0 Longview Terrace', '245', 'Sandgerði', 'IS');
insert into customer_address (customer_id, firstname, lastname, street_1, postcode, city, country_id) values (88, 'Dasya', 'Colloff', '6 Manufacturers Circle', '80140', 'Pak Phanang', 'TH');
insert into customer_address (customer_id, firstname, lastname, street_1, postcode, city, country_id) values (89, 'Hoyt', 'Doret', '7 Susan Junction', '3200', 'Concordia', 'AR');
insert into customer_address (customer_id, firstname, lastname, street_1, postcode, city, country_id) values (90, 'Nedi', 'Raunds', '61539 Little Fleur Terrace', '63180-000', 'Barbalha', 'BR');
insert into customer_address (customer_id, firstname, lastname, street_1, postcode, city, country_id) values (91, 'Clarita', 'Norcliff', '2 Vahlen Plaza', null, 'Pajannangger', 'ID');
insert into customer_address (customer_id, firstname, lastname, street_1, postcode, city, country_id) values (92, 'Krysta', 'Bywaters', '77680 Carpenter Alley', null, 'Citeureup', 'ID');
insert into customer_address (customer_id, firstname, lastname, street_1, postcode, city, country_id) values (93, 'Indira', 'Ruane', '126 Glacier Hill Trail', 'J7R', 'Saint-Eustache', 'CA');
insert into customer_address (customer_id, firstname, lastname, street_1, postcode, city, country_id) values (94, 'Hillery', 'McDell', '854 Tony Point', null, 'Jinbi', 'CN');
insert into customer_address (customer_id, firstname, lastname, street_1, postcode, city, country_id) values (95, 'Kayle', 'Freemantle', '8 Kings Terrace', null, 'Solosolo', 'WS');
insert into customer_address (customer_id, firstname, lastname, street_1, postcode, city, country_id) values (96, 'Andre', 'Jeffery', '13945 Coolidge Place', null, 'Salacgrīva', 'LV');
insert into customer_address (customer_id, firstname, lastname, street_1, postcode, city, country_id) values (97, 'Cynthea', 'Nisot', '8 Pankratz Pass', '165340', 'Vychegodskiy', 'RU');
insert into customer_address (customer_id, firstname, lastname, street_1, postcode, city, country_id) values (98, 'Reggy', 'Crackel', '8446 Sherman Parkway', null, 'Puntaru', 'ID');
insert into customer_address (customer_id, firstname, lastname, street_1, postcode, city, country_id) values (99, 'Bink', 'Smiz', '73704 Drewry Pass', '18763', 'Wilkes Barre', 'US');
insert into customer_address (customer_id, firstname, lastname, street_1, postcode, city, country_id) values (100, 'Marc', 'Gunter', '9 Sage Point', null, 'Āgaro', 'ET');
insert into customer_address (customer_id, firstname, lastname, street_1, postcode, city, country_id) values (1, 'Nanine', 'Tomasello', '6 Rutledge Point', null, 'Gerdu', 'ID');
insert into customer_address (customer_id, firstname, lastname, street_1, postcode, city, country_id) values (2, 'Erskine', 'Windham', '57 Del Sol Park', null, 'Chimboy Shahri', 'UZ');
insert into customer_address (customer_id, firstname, lastname, street_1, postcode, city, country_id) values (3, 'Bonita', 'Bradforth', '37 Clemons Court', '155526', 'Furmanov', 'RU');
insert into customer_address (customer_id, firstname, lastname, street_1, postcode, city, country_id) values (4, 'Deloris', 'Speight', '0 Dottie Park', '368692', 'Khiv', 'RU');
insert into customer_address (customer_id, firstname, lastname, street_1, postcode, city, country_id) values (5, 'Camala', 'Tansly', '4654 Londonderry Terrace', null, 'Aībak', 'AF');
insert into customer_address (customer_id, firstname, lastname, street_1, postcode, city, country_id) values (6, 'Antonino', 'Kort', '626 Cordelia Way', '632735', 'Kupino', 'RU');
insert into customer_address (customer_id, firstname, lastname, street_1, postcode, city, country_id) values (7, 'Dorena', 'Rumbelow', '4 Schurz Center', null, 'Huogezhuang', 'CN');
insert into customer_address (customer_id, firstname, lastname, street_1, postcode, city, country_id) values (8, 'Garrard', 'Canete', '7495 Independence Terrace', '2732', 'Cabugao', 'PH');
insert into customer_address (customer_id, firstname, lastname, street_1, postcode, city, country_id) values (9, 'Matthew', 'Gannicleff', '7 Nova Lane', '31422', 'Gorjani', 'HR');
insert into customer_address (customer_id, firstname, lastname, street_1, postcode, city, country_id) values (10, 'Zora', 'Aspinal', '96626 Maple Avenue', '636465', 'Kolpashevo', 'RU');
insert into customer_address (customer_id, firstname, lastname, street_1, postcode, city, country_id) values (11, 'Gladi', 'Pane', '34 Merchant Point', '06-413', 'Ciechanów', 'PL');
insert into customer_address (customer_id, firstname, lastname, street_1, postcode, city, country_id) values (12, 'Dalis', 'Seville', '9913 Macpherson Street', null, 'Daba', 'CN');
insert into customer_address (customer_id, firstname, lastname, street_1, postcode, city, country_id) values (13, 'Maddie', 'Heindl', '2508 Goodland Avenue', null, 'Yogyakarta', 'ID');
insert into customer_address (customer_id, firstname, lastname, street_1, postcode, city, country_id) values (14, 'Megan', 'Karim', '030 Lillian Lane', null, 'Bayan Gol', 'CN');
insert into customer_address (customer_id, firstname, lastname, street_1, postcode, city, country_id) values (15, 'Diarmid', 'Sturdy', '3639 Melvin Street', null, 'Quthing', 'LS');
insert into customer_address (customer_id, firstname, lastname, street_1, postcode, city, country_id) values (16, 'Woody', 'Huffy', '23263 Morningstar Trail', '34064 CEDEX 2', 'Montpellier', 'FR');
insert into customer_address (customer_id, firstname, lastname, street_1, postcode, city, country_id) values (17, 'Brittne', 'Bienvenu', '412 Maywood Avenue', '238411', 'Zheleznodorozhnyy', 'RU');
insert into customer_address (customer_id, firstname, lastname, street_1, postcode, city, country_id) values (18, 'Rod', 'Orr', '323 Muir Parkway', null, 'Halteu', 'ID');
insert into customer_address (customer_id, firstname, lastname, street_1, postcode, city, country_id) values (19, 'Caitrin', 'Robbeke', '906 Namekagon Place', '8430', 'El Bolsón', 'AR');
insert into customer_address (customer_id, firstname, lastname, street_1, postcode, city, country_id) values (20, 'Dwain', 'Gregorowicz', '4 Upham Pass', '7008', 'Payao', 'PH');
insert into customer_address (customer_id, firstname, lastname, street_1, postcode, city, country_id) values (21, 'Menard', 'Dowty', '5065 Monument Plaza', null, 'Fais', 'FM');
insert into customer_address (customer_id, firstname, lastname, street_1, postcode, city, country_id) values (22, 'Mathe', 'Gilman', '8073 Almo Point', null, 'Hanjianglu', 'CN');
insert into customer_address (customer_id, firstname, lastname, street_1, postcode, city, country_id) values (23, 'Elly', 'Clipson', '20227 Stone Corner Junction', null, 'Buraen', 'ID');
insert into customer_address (customer_id, firstname, lastname, street_1, postcode, city, country_id) values (24, 'Mendie', 'Burling', '469 Grayhawk Street', '6607', 'Silago', 'PH');
insert into customer_address (customer_id, firstname, lastname, street_1, postcode, city, country_id) values (25, 'Trace', 'Alchin', '99130 Boyd Point', '452815', 'Mesyagutovo', 'RU');
insert into customer_address (customer_id, firstname, lastname, street_1, postcode, city, country_id) values (26, 'Tyler', 'Josefs', '90603 Corben Street', null, 'Agadez', 'NE');
insert into customer_address (customer_id, firstname, lastname, street_1, postcode, city, country_id) values (27, 'Petronille', 'Chalk', '10 Barnett Lane', null, 'Buchach', 'UA');
insert into customer_address (customer_id, firstname, lastname, street_1, postcode, city, country_id) values (28, 'Allin', 'Bewick', '54 Graedel Way', '59280-000', 'Macaíba', 'BR');
insert into customer_address (customer_id, firstname, lastname, street_1, postcode, city, country_id) values (29, 'Pearline', 'Thiem', '366 Carey Park', '2000-452', 'Alqueidão', 'PT');
insert into customer_address (customer_id, firstname, lastname, street_1, postcode, city, country_id) values (30, 'Keen', 'Oldford', '508 John Wall Park', '760 01', 'Zlín', 'CZ');
insert into customer_address (customer_id, firstname, lastname, street_1, postcode, city, country_id) values (31, 'Adelle', 'Fieldsend', '544 Stang Center', null, 'Balung Barat', 'ID');
insert into customer_address (customer_id, firstname, lastname, street_1, postcode, city, country_id) values (32, 'Ashien', 'Ruggen', '5843 Prairieview Terrace', '69470-000', 'Tefé', 'BR');
insert into customer_address (customer_id, firstname, lastname, street_1, postcode, city, country_id) values (33, 'Oswell', 'Gossage', '9 Coolidge Trail', '42304 CEDEX', 'Roanne', 'FR');
insert into customer_address (customer_id, firstname, lastname, street_1, postcode, city, country_id) values (34, 'Janine', 'Tuttiett', '24 Kings Terrace', null, 'Mingelchaur', 'AZ');
insert into customer_address (customer_id, firstname, lastname, street_1, postcode, city, country_id) values (35, 'Lillian', 'Gare', '3 Talisman Junction', null, 'Qozonketkan', 'UZ');
insert into customer_address (customer_id, firstname, lastname, street_1, postcode, city, country_id) values (36, 'Candida', 'Ainsby', '2 Eastlawn Parkway', null, 'Celendín', 'PE');
insert into customer_address (customer_id, firstname, lastname, street_1, postcode, city, country_id) values (37, 'Mersey', 'Delos', '42 Rowland Point', '44795', 'Bochum', 'DE');
insert into customer_address (customer_id, firstname, lastname, street_1, postcode, city, country_id) values (38, 'Lon', 'Tovey', '2 Emmet Road', null, 'Béoumi', 'CI');
insert into customer_address (customer_id, firstname, lastname, street_1, postcode, city, country_id) values (39, 'Ros', 'Copello', '154 Sutteridge Park', null, 'Chkalov', 'TJ');
insert into customer_address (customer_id, firstname, lastname, street_1, postcode, city, country_id) values (40, 'Lulita', 'Ballantine', '18 Washington Park', null, 'Shanlian', 'CN');
insert into customer_address (customer_id, firstname, lastname, street_1, postcode, city, country_id) values (41, 'Nataline', 'Stavers', '0441 North Circle', '362 63', 'Dalovice', 'CZ');
insert into customer_address (customer_id, firstname, lastname, street_1, postcode, city, country_id) values (42, 'Katine', 'Causbey', '150 Shasta Place', null, 'Taimaman', 'ID');
insert into customer_address (customer_id, firstname, lastname, street_1, postcode, city, country_id) values (43, 'Carlene', 'Grove', '69537 Briar Crest Point', null, 'Savelugu', 'GH');
insert into customer_address (customer_id, firstname, lastname, street_1, postcode, city, country_id) values (44, 'Merrielle', 'Bedwell', '771 Riverside Crossing', null, 'Seredyna-Buda', 'UA');
insert into customer_address (customer_id, firstname, lastname, street_1, postcode, city, country_id) values (45, 'Doloritas', 'Atrill', '020 Golf Point', null, 'Quebracho', 'UY');
insert into customer_address (customer_id, firstname, lastname, street_1, postcode, city, country_id) values (46, 'Syman', 'Alwell', '7265 Butterfield Lane', null, 'Betong', 'ID');
insert into customer_address (customer_id, firstname, lastname, street_1, postcode, city, country_id) values (47, 'Monte', 'McQuilkin', '196 Milwaukee Alley', '3870-207', 'Pardelhas', 'PT');
insert into customer_address (customer_id, firstname, lastname, street_1, postcode, city, country_id) values (48, 'Elsa', 'Rooney', '2 Southridge Crossing', '1097', 'Budapest', 'HU');
insert into customer_address (customer_id, firstname, lastname, street_1, postcode, city, country_id) values (49, 'Antoinette', 'Hubbucks', '6 Dwight Avenue', null, 'Tiabaya', 'PE');
insert into customer_address (customer_id, firstname, lastname, street_1, postcode, city, country_id) values (50, 'Gilemette', 'Bowerbank', '316 Browning Street', null, 'Bihać', 'BA');
insert into customer_address (customer_id, firstname, lastname, street_1, postcode, city, country_id) values (1, 'Far', 'Birkbeck', '1477 Mockingbird Drive', null, 'Leping', 'CN');
insert into customer_address (customer_id, firstname, lastname, street_1, postcode, city, country_id) values (2, 'Paulo', 'Cardis', '41 Kedzie Lane', null, 'Umuquena', 'VE');
insert into customer_address (customer_id, firstname, lastname, street_1, postcode, city, country_id) values (3, 'Mart', 'MacClure', '73043 Kingsford Plaza', '21314', 'Jesenice', 'HR');
insert into customer_address (customer_id, firstname, lastname, street_1, postcode, city, country_id) values (4, 'Elladine', 'Ions', '0 Village Green Circle', null, 'Troyits’ke', 'UA');
insert into customer_address (customer_id, firstname, lastname, street_1, postcode, city, country_id) values (5, 'Jacki', 'Baudet', '7556 Carberry Crossing', '16130', 'Bang Racham', 'TH');
insert into customer_address (customer_id, firstname, lastname, street_1, postcode, city, country_id) values (6, 'Joyan', 'Furmonger', '88 Pine View Street', null, 'Dushk', 'AL');
insert into customer_address (customer_id, firstname, lastname, street_1, postcode, city, country_id) values (7, 'Kirsteni', 'Maciejak', '6 Graceland Place', null, 'Morcolla', 'PE');
insert into customer_address (customer_id, firstname, lastname, street_1, postcode, city, country_id) values (8, 'Hali', 'Tomet', '249 Corry Park', '4950-416', 'Monção', 'PT');
insert into customer_address (customer_id, firstname, lastname, street_1, postcode, city, country_id) values (9, 'Quintilla', 'Ferandez', '12170 Debs Circle', null, 'Myronivka', 'UA');
insert into customer_address (customer_id, firstname, lastname, street_1, postcode, city, country_id) values (10, 'Conney', 'Gosland', '57356 Namekagon Parkway', null, 'Brka', 'BA');
insert into customer_address (customer_id, firstname, lastname, street_1, postcode, city, country_id) values (11, 'Dotty', 'Greedier', '54009 Hooker Junction', '659690', 'Soloneshnoye', 'RU');
insert into customer_address (customer_id, firstname, lastname, street_1, postcode, city, country_id) values (12, 'Katusha', 'Beane', '36 Spohn Hill', '263 01', 'Dobříš', 'CZ');
insert into customer_address (customer_id, firstname, lastname, street_1, postcode, city, country_id) values (13, 'Celestina', 'Shorto', '36542 Burning Wood Circle', '152 07', 'Södertälje', 'SE');
insert into customer_address (customer_id, firstname, lastname, street_1, postcode, city, country_id) values (14, 'Karlee', 'Wenham', '860 Bellgrove Drive', '15640-000', 'Tomé Açu', 'BR');
insert into customer_address (customer_id, firstname, lastname, street_1, postcode, city, country_id) values (15, 'Arabela', 'Bridie', '6 Buell Plaza', '057068', 'Cañasgordas', 'CO');
insert into customer_address (customer_id, firstname, lastname, street_1, postcode, city, country_id) values (16, 'Noby', 'Bard', '037 Sundown Junction', null, 'El Corozal', 'HN');
insert into customer_address (customer_id, firstname, lastname, street_1, postcode, city, country_id) values (17, 'Lorilee', 'Bontine', '63896 Old Shore Avenue', null, 'Luzhuangzi', 'CN');
insert into customer_address (customer_id, firstname, lastname, street_1, postcode, city, country_id) values (18, 'Josey', 'Wartonby', '009 Coolidge Lane', null, 'Kumane', 'RS');
insert into customer_address (customer_id, firstname, lastname, street_1, postcode, city, country_id) values (19, 'Win', 'Casillis', '48 Westerfield Junction', null, 'Krajan', 'ID');
insert into customer_address (customer_id, firstname, lastname, street_1, postcode, city, country_id) values (20, 'Annabelle', 'Scedall', '22 Sutherland Circle', null, 'Jeonju', 'KR');